i need you to create mermaid bd  er scheme based on this:
User{
    Id
    Login
    Email
    Password
}
TaskType{
    Id
    Name
    Complexity
}
Task{
    Id
    Name
    UserId
    TaskTypeId
    Description
}